-- PRY2204_Exp3_S7_Script_unico_DEMO_orden_ok.sql
-- Corrección: mover el poblamiento de PERSONAL ANTES de los informes para que se vean las rentas.

/************************************************************
      Limpieza
************************************************************/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE TITULACION CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PERSONAL CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COMPANIA CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COMUNA CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE REGION CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TITULO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DOMINIO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE IDIOMA CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ESTADO_CIVIL CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE GENERO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COMPANIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COMUNA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

/************************************************************
  Tablas
************************************************************/

-- REGION
CREATE TABLE REGION (
    ID_REGION     NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 7 INCREMENT BY 2) NOT NULL,
    NOMBRE_REGION VARCHAR2(80) NOT NULL,
    CONSTRAINT PK_REGION PRIMARY KEY (ID_REGION),
    CONSTRAINT UN_REGION_NOMBRE UNIQUE (NOMBRE_REGION)
);

-- COMUNA
CREATE TABLE COMUNA (
    ID_COMUNA     NUMBER NOT NULL,
    NOMBRE_COMUNA VARCHAR2(100) NOT NULL,
    ID_REGION     NUMBER NOT NULL,
    CONSTRAINT PK_COMUNA PRIMARY KEY (ID_COMUNA),
    CONSTRAINT UN_COMUNA_NOMBRE UNIQUE (NOMBRE_COMUNA),
    CONSTRAINT FK_COMUNA_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION)
);
CREATE SEQUENCE SEQ_COMUNA START WITH 1101 INCREMENT BY 6 NOCACHE;

-- GENERO
CREATE TABLE GENERO (
    ID_GENERO NUMBER NOT NULL,
    NOMBRE    VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_GENERO PRIMARY KEY (ID_GENERO),
    CONSTRAINT UN_GENERO_NOMBRE UNIQUE (NOMBRE)
);

-- ESTADO_CIVIL
CREATE TABLE ESTADO_CIVIL (
    ID_ESTADO_CIVIL NUMBER NOT NULL,
    NOMBRE          VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_ESTADO_CIVIL PRIMARY KEY (ID_ESTADO_CIVIL),
    CONSTRAINT UN_ESTADO_CIVIL_NOMBRE UNIQUE (NOMBRE)
);

-- IDIOMA
CREATE TABLE IDIOMA (
    ID_IDIOMA NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 25 INCREMENT BY 3) NOT NULL,
    NOMBRE    VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_IDIOMA PRIMARY KEY (ID_IDIOMA),
    CONSTRAINT UN_IDIOMA_NOMBRE UNIQUE (NOMBRE)
);

-- DOMINIO
CREATE TABLE DOMINIO (
    ID_DOMINIO NUMBER NOT NULL,
    NOMBRE     VARCHAR2(80) NOT NULL,
    CONSTRAINT PK_DOMINIO PRIMARY KEY (ID_DOMINIO),
    CONSTRAINT UN_DOMINIO_NOMBRE UNIQUE (NOMBRE)
);

-- TITULO
CREATE TABLE TITULO (
    ID_TITULO NUMBER NOT NULL,
    NOMBRE    VARCHAR2(120) NOT NULL,
    CONSTRAINT PK_TITULO PRIMARY KEY (ID_TITULO),
    CONSTRAINT UN_TITULO_NOMBRE UNIQUE (NOMBRE)
);

-- COMPANIA
CREATE TABLE COMPANIA (
    ID_COMPANIA        NUMBER NOT NULL,
    NOMBRE             VARCHAR2(120) NOT NULL,
    DIRECCION          VARCHAR2(200),
    ID_COMUNA          NUMBER,
    PORCENTAJE_AUMENTO NUMBER(5,2) DEFAULT 0,
    CONSTRAINT PK_COMPANIA PRIMARY KEY (ID_COMPANIA),
    CONSTRAINT UN_COMPANIA_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT FK_COMPANIA_COMUNA FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA(ID_COMUNA)
);
CREATE SEQUENCE SEQ_COMPANIA START WITH 10 INCREMENT BY 5 NOCACHE;

-- PERSONAL
CREATE TABLE PERSONAL (
    ID_PERSONAL     NUMBER NOT NULL,
    RUN_NUM         NUMBER(8,0) NOT NULL,
    RUN_DV          CHAR(1)     NOT NULL,
    NOMBRES         VARCHAR2(80) NOT NULL,
    APELLIDOS       VARCHAR2(80) NOT NULL,
    EMAIL           VARCHAR2(120),
    SUELDO          NUMBER(10,0) NOT NULL,
    ID_COMPANIA     NUMBER NOT NULL,
    ID_COMUNA       NUMBER,
    ID_ESTADO_CIVIL NUMBER,
    ID_GENERO       NUMBER,
    CONSTRAINT PK_PERSONAL PRIMARY KEY (ID_PERSONAL),
    CONSTRAINT FK_PERSONAL_COMPANIA FOREIGN KEY (ID_COMPANIA)     REFERENCES COMPANIA(ID_COMPANIA),
    CONSTRAINT FK_PERSONAL_COMUNA   FOREIGN KEY (ID_COMUNA)       REFERENCES COMUNA(ID_COMUNA),
    CONSTRAINT FK_PERSONAL_EC       FOREIGN KEY (ID_ESTADO_CIVIL) REFERENCES ESTADO_CIVIL(ID_ESTADO_CIVIL),
    CONSTRAINT FK_PERSONAL_GENERO   FOREIGN KEY (ID_GENERO)       REFERENCES GENERO(ID_GENERO)
);

-- TITULACION
CREATE TABLE TITULACION (
    ID_TITULACION   NUMBER NOT NULL,
    ID_PERSONAL     NUMBER NOT NULL,
    ID_TITULO       NUMBER NOT NULL,
    ID_DOMINIO      NUMBER,
    ID_IDIOMA       NUMBER,
    FECHA_OBTENCION DATE,
    CONSTRAINT PK_TITULACION PRIMARY KEY (ID_TITULACION),
    CONSTRAINT FK_TITULACION_PERSONAL FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL(ID_PERSONAL),
    CONSTRAINT FK_TITULACION_TITULO   FOREIGN KEY (ID_TITULO)   REFERENCES TITULO(ID_TITULO),
    CONSTRAINT FK_TITULACION_DOMINIO  FOREIGN KEY (ID_DOMINIO)  REFERENCES DOMINIO(ID_DOMINIO),
    CONSTRAINT FK_TITULACION_IDIOMA   FOREIGN KEY (ID_IDIOMA)   REFERENCES IDIOMA(ID_IDIOMA),
    CONSTRAINT UN_TITULACION_UNICA UNIQUE (ID_PERSONAL, ID_TITULO)
);

/************************************************************
    Reglas de negocio
************************************************************/

ALTER TABLE PERSONAL ADD CONSTRAINT UN_PERSONAL_EMAIL UNIQUE (EMAIL);
ALTER TABLE PERSONAL ADD CONSTRAINT CK_PERSONAL_RUN_DV
  CHECK (RUN_DV IN ('0','1','2','3','4','5','6','7','8','9','K'));
ALTER TABLE PERSONAL ADD CONSTRAINT CK_PERSONAL_SUELDO_MIN
  CHECK (SUELDO >= 450000);

/************************************************************
    Poblamiento
************************************************************/

-- REGION
INSERT INTO REGION (NOMBRE_REGION) VALUES ('Arica y Parinacota');
INSERT INTO REGION (NOMBRE_REGION) VALUES ('Tarapacá');
INSERT INTO REGION (NOMBRE_REGION) VALUES ('Antofagasta');
INSERT INTO REGION (NOMBRE_REGION) VALUES ('Atacama');
INSERT INTO REGION (NOMBRE_REGION) VALUES ('Coquimbo');
INSERT INTO REGION (NOMBRE_REGION) VALUES ('Valparaíso');
INSERT INTO REGION (NOMBRE_REGION) VALUES ('Metropolitana de Santiago');

-- COMUNA
INSERT INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)
VALUES (SEQ_COMUNA.NEXTVAL, 'Arica',       (SELECT ID_REGION FROM REGION WHERE NOMBRE_REGION='Arica y Parinacota'));
INSERT INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)
VALUES (SEQ_COMUNA.NEXTVAL, 'Iquique',     (SELECT ID_REGION FROM REGION WHERE NOMBRE_REGION='Tarapacá'));
INSERT INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)
VALUES (SEQ_COMUNA.NEXTVAL, 'Antofagasta', (SELECT ID_REGION FROM REGION WHERE NOMBRE_REGION='Antofagasta'));
INSERT INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)
VALUES (SEQ_COMUNA.NEXTVAL, 'Copiapó',     (SELECT ID_REGION FROM REGION WHERE NOMBRE_REGION='Atacama'));
INSERT INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)
VALUES (SEQ_COMUNA.NEXTVAL, 'La Serena',   (SELECT ID_REGION FROM REGION WHERE NOMBRE_REGION='Coquimbo'));
INSERT INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)
VALUES (SEQ_COMUNA.NEXTVAL, 'Valparaíso',  (SELECT ID_REGION FROM REGION WHERE NOMBRE_REGION='Valparaíso'));
INSERT INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)
VALUES (SEQ_COMUNA.NEXTVAL, 'Santiago',    (SELECT ID_REGION FROM REGION WHERE NOMBRE_REGION='Metropolitana de Santiago'));

-- IDIOMA
INSERT INTO IDIOMA (NOMBRE) VALUES ('Español');
INSERT INTO IDIOMA (NOMBRE) VALUES ('Inglés');
INSERT INTO IDIOMA (NOMBRE) VALUES ('Francés');
INSERT INTO IDIOMA (NOMBRE) VALUES ('Portugués');

-- COMPANIA
INSERT INTO COMPANIA (ID_COMPANIA, NOMBRE, DIRECCION, ID_COMUNA, PORCENTAJE_AUMENTO)
VALUES (SEQ_COMPANIA.NEXTVAL, 'Andina Retail Norte',   'Av. Principal 123',
        (SELECT ID_COMUNA FROM COMUNA WHERE NOMBRE_COMUNA='Santiago'),     7.5);
INSERT INTO COMPANIA (ID_COMPANIA, NOMBRE, DIRECCION, ID_COMUNA, PORCENTAJE_AUMENTO)
VALUES (SEQ_COMPANIA.NEXTVAL, 'Andina Retail Sur',     'Calle Norte 456',
        (SELECT ID_COMUNA FROM COMUNA WHERE NOMBRE_COMUNA='Valparaíso'),   5.0);
INSERT INTO COMPANIA (ID_COMPANIA, NOMBRE, DIRECCION, ID_COMUNA, PORCENTAJE_AUMENTO)
VALUES (SEQ_COMPANIA.NEXTVAL, 'Austral Hogar',         'Pasaje Sur 789',
        (SELECT ID_COMUNA FROM COMUNA WHERE NOMBRE_COMUNA='La Serena'),    6.2);
INSERT INTO COMPANIA (ID_COMPANIA, NOMBRE, DIRECCION, ID_COMUNA, PORCENTAJE_AUMENTO)
VALUES (SEQ_COMPANIA.NEXTVAL, 'Pacífico Tecnología',   'Ruta 5 Km 10',
        (SELECT ID_COMUNA FROM COMUNA WHERE NOMBRE_COMUNA='Antofagasta'),  4.0);
INSERT INTO COMPANIA (ID_COMPANIA, NOMBRE, DIRECCION, ID_COMUNA, PORCENTAJE_AUMENTO)
VALUES (SEQ_COMPANIA.NEXTVAL, 'Norte Mayorista',       'Av. Costanera 321',
        (SELECT ID_COMUNA FROM COMUNA WHERE NOMBRE_COMUNA='Iquique'),      8.0);
INSERT INTO COMPANIA (ID_COMPANIA, NOMBRE, DIRECCION, ID_COMUNA, PORCENTAJE_AUMENTO)
VALUES (SEQ_COMPANIA.NEXTVAL, 'Cordillera Logística',  'Calle Larga 654',
        (SELECT ID_COMUNA FROM COMUNA WHERE NOMBRE_COMUNA='Copiapó'),      3.0);
INSERT INTO COMPANIA (ID_COMPANIA, NOMBRE, DIRECCION, ID_COMUNA, PORCENTAJE_AUMENTO)
VALUES (SEQ_COMPANIA.NEXTVAL, 'Valle Alimentos',       'Av. Centro 987',
        (SELECT ID_COMUNA FROM COMUNA WHERE NOMBRE_COMUNA='Arica'),        6.8);

COMMIT;

/************************************************************
    Poblamiento de PERSONAL
************************************************************/

INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 1, 11111111, 'K', 'Ana',  'González', NULL, 750000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Andina Retail Norte';
INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 2, 22222222, '9', 'Luis', 'Pérez',    NULL, 980000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Andina Retail Norte';

INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 3, 33333333, '8', 'María','Rojas',    NULL, 620000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Andina Retail Sur';
INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 4, 44444444, '7', 'Joel', 'Soto',     NULL, 890000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Andina Retail Sur';

INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 5, 55555555, '6', 'Iris', 'Aguilar',  NULL, 540000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Austral Hogar';
INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 6, 66666666, '5', 'Diego','Campos',   NULL, 810000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Austral Hogar';

INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 7, 77777777, '4', 'Sofía','Vega',     NULL, 700000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Pacífico Tecnología';
INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 8, 88888888, '3', 'Pablo','Reyes',    NULL, 910000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Pacífico Tecnología';

INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 9, 99999999, '2', 'Valeska','Silva',  NULL, 455000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Norte Mayorista';
INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 10, 12345678, 'K', 'León', 'Maldonado',NULL, 500000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Norte Mayorista';

INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 11, 13579135, '1', 'Camila','Figueroa',NULL, 730000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Cordillera Logística';
INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 12, 24682468, '0', 'Ricardo','Ortiz',  NULL, 870000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Cordillera Logística';

INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 13, 31415926, '9', 'Elisa','Cáceres',  NULL, 600000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Valle Alimentos';
INSERT INTO PERSONAL (ID_PERSONAL, RUN_NUM, RUN_DV, NOMBRES, APELLIDOS, EMAIL, SUELDO, ID_COMPANIA)
SELECT 14, 27182818, '8', 'Tomás','Lara',     NULL, 920000, C.ID_COMPANIA FROM COMPANIA C WHERE C.NOMBRE='Valle Alimentos';

COMMIT;

/************************************************************
    Informes
************************************************************/

-- Informe 1
SELECT
  COMPANIA.NOMBRE AS "Nombre Empresa",
  COMPANIA.DIRECCION || ', ' || COMUNA.NOMBRE_COMUNA || ' (' || REGION.NOMBRE_REGION || ')' AS "Dirección",
  ROUND(NVL(AVG(PERSONAL.SUELDO), 0), 0) AS "Renta Promedio",
  ROUND(NVL(AVG(PERSONAL.SUELDO), 0) * (1 + NVL(COMPANIA.PORCENTAJE_AUMENTO,0)/100), 0) AS "Simulación de Renta Promedio"
FROM COMPANIA
LEFT JOIN PERSONAL ON PERSONAL.ID_COMPANIA = COMPANIA.ID_COMPANIA
LEFT JOIN COMUNA   ON COMUNA.ID_COMUNA     = COMPANIA.ID_COMUNA
LEFT JOIN REGION   ON REGION.ID_REGION     = COMUNA.ID_REGION
GROUP BY COMPANIA.NOMBRE, COMPANIA.DIRECCION, COMUNA.NOMBRE_COMUNA, REGION.NOMBRE_REGION, COMPANIA.PORCENTAJE_AUMENTO
ORDER BY "Renta Promedio" DESC, "Nombre Empresa" ASC;

-- Informe 2
SELECT
  COMPANIA.ID_COMPANIA AS "ID Empresa",
  COMPANIA.NOMBRE      AS "Nombre Empresa",
  ROUND(NVL(AVG(PERSONAL.SUELDO), 0), 0) AS "Renta Actual",
  ROUND(NVL(COMPANIA.PORCENTAJE_AUMENTO,0) + 15, 2) AS "Porcentaje Ajustado",
  ROUND(NVL(AVG(PERSONAL.SUELDO), 0) * (1 + (NVL(COMPANIA.PORCENTAJE_AUMENTO,0) + 15)/100), 0) AS "Renta Final"
FROM COMPANIA
LEFT JOIN PERSONAL ON PERSONAL.ID_COMPANIA = COMPANIA.ID_COMPANIA
GROUP BY COMPANIA.ID_COMPANIA, COMPANIA.NOMBRE, COMPANIA.PORCENTAJE_AUMENTO
ORDER BY "Renta Actual" ASC, "Nombre Empresa" DESC;

-- FIN